import type { Book } from "@/components/book-card";

// Sample books copied from barnesandnoble.com/collections/books (Oct 2026).
// Placeholder until the DB is set up using Drizzle. Delete this file once real data is in.
// Covers load from cdn.shopify.com, which is allowed in next.config.ts
//
// Tags are lowercase w/ dashes so they're easy to compare in code:
//   sections: bestseller, trending, new-release, coming-soon, special-edition, paperback-pick
//   genre:    fiction, nonfiction, kids
//   format:   hardcover, paperback, exclusive, signed
// Builds a cover image URL from the ISBN since they all follow the same pattern
const COVER = (isbn13: string) =>
  `https://cdn.shopify.com/s/files/1/0674/5433/7265/files/${isbn13}_p0.jpg`;

export const sampleBooks: Book[] = [
  {
    isbn13: "9781682818084",
    title: "Threshing Day (Wing and Claw Collection)",
    author: "Rebecca Yarros",
    price: 24.99,
    tags: ["bestseller", "fiction", "special-edition"],
    img_src: COVER("9781682818084"),
    img_alt: "Cover of Threshing Day (Wing and Claw Collection)",
  },
  {
    isbn13: "9781639739134",
    title: "A Court of Splintered Harmony (A Court of Thorns and Roses Series #6)",
    author: "Sarah J. Maas",
    price: 32,
    tags: ["bestseller", "trending", "fiction", "hardcover"],
    img_src: COVER("9781639739134"),
    img_alt: "Cover of A Court of Splintered Harmony (A Court of Thorns and Roses Series #6)",
  },
  {
    isbn13: "9781668236512",
    title: "Theo of Golden: A Novel",
    author: "Allen Levi",
    price: 20,
    tags: ["bestseller", "fiction", "paperback"],
    img_src: COVER("9781668236512"),
    img_alt: "Cover of Theo of Golden: A Novel",
  },
  {
    isbn13: "9798347121151",
    title: "Falling Like Leaves (B&N Exclusive Edition)",
    author: "Misty Wilson",
    price: 12.99,
    tags: ["bestseller", "fiction", "exclusive"],
    img_src: COVER("9798347121151"),
    img_alt: "Cover of Falling Like Leaves (B&N Exclusive Edition)",
  },
  {
    isbn13: "9798260200568",
    title: "A Court of Forgotten Melody (A Court of Thorns and Roses Series #7)",
    author: "Sarah J. Maas",
    price: 38,
    tags: ["bestseller", "fiction", "hardcover"],
    img_src: COVER("9798260200568"),
    img_alt: "Cover of A Court of Forgotten Melody (A Court of Thorns and Roses Series #7)",
  },
  {
    isbn13: "9781954118812",
    title: "The Calamity Club: A Novel",
    author: "Kathryn Stockett",
    price: 30,
    tags: ["bestseller", "fiction", "hardcover"],
    img_src: COVER("9781954118812"),
    img_alt: "Cover of The Calamity Club: A Novel",
  },
  {
    isbn13: "9780593820254",
    title: "Dungeon Crawler Carl (Dungeon Crawler Carl Series #1)",
    author: "Matt Dinniman",
    price: 20,
    tags: ["bestseller", "trending", "fiction", "paperback"],
    img_src: COVER("9780593820254"),
    img_alt: "Cover of Dungeon Crawler Carl (Dungeon Crawler Carl Series #1)",
  },
  {
    isbn13: "9780385550543",
    title: "The French Illusion: A Novel",
    author: "John Grisham",
    price: 24.5,
    tags: ["bestseller", "fiction", "hardcover"],
    img_src: COVER("9780385550543"),
    img_alt: "Cover of The French Illusion: A Novel",
  },
  {
    isbn13: "9798347124121",
    title: "Trust Fall (B&N Exclusive Edition)",
    author: "Lynn Painter",
    price: 18.99,
    tags: ["bestseller", "fiction", "exclusive"],
    img_src: COVER("9798347124121"),
    img_alt: "Cover of Trust Fall (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781538784051",
    title: "Verity",
    author: "Colleen Hoover",
    price: 15.99,
    tags: ["bestseller", "trending", "fiction", "paperback"],
    img_src: COVER("9781538784051"),
    img_alt: "Cover of Verity",
  },
  {
    isbn13: "9780316608329",
    title: "The Knave and the Moon (B&N Exclusive Edition)",
    author: "Rachel Gillig",
    price: 25,
    tags: ["bestseller", "fiction", "exclusive"],
    img_src: COVER("9780316608329"),
    img_alt: "Cover of The Knave and the Moon (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781680108354",
    title: "Frankenkitty (B&N Exclusive Edition)",
    author: "Maudie Powell-Tuck",
    price: 18.99,
    tags: ["bestseller", "kids", "exclusive"],
    img_src: COVER("9781680108354"),
    img_alt: "Cover of Frankenkitty (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781454961796",
    title: "Murdoku: 80 Murder Mystery Logic Puzzles",
    author: "Manuel Garand",
    price: 18.99,
    tags: ["bestseller", "nonfiction", "paperback"],
    img_src: COVER("9781454961796"),
    img_alt: "Cover of Murdoku: 80 Murder Mystery Logic Puzzles",
  },
  {
    isbn13: "9780593135228",
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: 22,
    tags: ["bestseller", "trending", "fiction", "paperback"],
    img_src: COVER("9780593135228"),
    img_alt: "Cover of Project Hail Mary",
  },
  {
    isbn13: "9780063582002",
    title: "Partita: A Novel (B&N Exclusive Edition)",
    author: "Barbara Kingsolver",
    price: 27,
    tags: ["new-release", "fiction", "exclusive"],
    img_src: COVER("9780063582002"),
    img_alt: "Cover of Partita: A Novel (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781324131656",
    title: "Blockers: Rebels in the Deep State",
    author: "Michael Lewis",
    price: 26.99,
    tags: ["new-release", "nonfiction", "hardcover"],
    img_src: COVER("9781324131656"),
    img_alt: "Cover of Blockers: Rebels in the Deep State",
  },
  {
    isbn13: "9781668233092",
    title: "Other Worlds Than These (The Talisman #3)",
    author: "Stephen King, Peter Straub",
    price: 30,
    tags: ["new-release", "trending", "fiction", "hardcover"],
    img_src: COVER("9781668233092"),
    img_alt: "Cover of Other Worlds Than These (The Talisman #3)",
  },
  {
    isbn13: "9780525562238",
    title: "The Rush: California Gold, the Civil War, and the Making of the Modern World",
    author: "Nathaniel Philbrick",
    price: 35,
    tags: ["new-release", "nonfiction", "hardcover"],
    img_src: COVER("9780525562238"),
    img_alt: "Cover of The Rush: California Gold, the Civil War, and the Making of the Modern World",
  },
  {
    isbn13: "9781464249648",
    title: "The Witch (Deluxe Edition)",
    author: "Freida McFadden",
    price: 24.99,
    tags: ["new-release", "fiction", "hardcover"],
    img_src: COVER("9781464249648"),
    img_alt: "Cover of The Witch (Deluxe Edition)",
  },
  {
    isbn13: "9780593655276",
    title: "Sleeping Beauties: Why Good Ideas Go Dormant and How They Wake Up",
    author: "David Byrne",
    price: 33,
    tags: ["new-release", "nonfiction", "hardcover"],
    img_src: COVER("9780593655276"),
    img_alt: "Cover of Sleeping Beauties: Why Good Ideas Go Dormant and How They Wake Up",
  },
  {
    isbn13: "9781250474940",
    title: "Victorious (B&N Exclusive Edition)",
    author: "V. E. Schwab",
    price: 28.99,
    tags: ["new-release", "trending", "fiction", "exclusive"],
    img_src: COVER("9781250474940"),
    img_alt: "Cover of Victorious (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781546008873",
    title: "Return to the Shack: A Journey into Redemption",
    author: "William Paul Young",
    price: 27,
    tags: ["new-release", "fiction", "hardcover"],
    img_src: COVER("9781546008873"),
    img_alt: "Cover of Return to the Shack: A Journey into Redemption",
  },
  {
    isbn13: "9781984860088",
    title: "Ottolenghi Simple Too: A Cookbook",
    author: "Yotam Ottolenghi",
    price: 42,
    tags: ["new-release", "nonfiction", "hardcover"],
    img_src: COVER("9781984860088"),
    img_alt: "Cover of Ottolenghi Simple Too: A Cookbook",
  },
  {
    isbn13: "9781538782224",
    title: "One Helluva Ride",
    author: "Michael Douglas",
    price: 17.5,
    tags: ["new-release", "nonfiction", "hardcover"],
    img_src: COVER("9781538782224"),
    img_alt: "Cover of One Helluva Ride",
  },
  {
    isbn13: "9798217154852",
    title: "The Third Eye: Early Photographs",
    author: "George Harrison",
    price: 62,
    tags: ["new-release", "nonfiction", "hardcover"],
    img_src: COVER("9798217154852"),
    img_alt: "Cover of The Third Eye: Early Photographs",
  },
  {
    isbn13: "9780316603782",
    title: "The American Way of Killing: The Invention of an Epidemic",
    author: "Malcolm Gladwell",
    price: 31,
    tags: ["new-release", "nonfiction", "hardcover"],
    img_src: COVER("9780316603782"),
    img_alt: "Cover of The American Way of Killing: The Invention of an Epidemic",
  },
  {
    isbn13: "9798217379743",
    title: "Swan Song",
    author: "Charles Spencer",
    price: 24.5,
    tags: ["new-release", "nonfiction", "hardcover"],
    img_src: COVER("9798217379743"),
    img_alt: "Cover of Swan Song",
  },
  {
    isbn13: "9781682818251",
    title: "Seven and the Swift (Shield of Sparrows Series #3)",
    author: "Devney Perry",
    price: 27.99,
    tags: ["coming-soon", "fiction", "hardcover"],
    img_src: COVER("9781682818251"),
    img_alt: "Cover of Seven and the Swift (Shield of Sparrows Series #3)",
  },
  {
    isbn13: "9780316616324",
    title: "I'll Believe in Anything: The Making of Heated Rivalry Season 1 (The Annotated Scripts) (B&N Exclusive Edition)",
    author: "Jacob Tierney",
    price: 29,
    tags: ["coming-soon", "nonfiction", "exclusive"],
    img_src: COVER("9780316616324"),
    img_alt: "Cover of I'll Believe in Anything: The Making of Heated Rivalry Season 1 (The Annotated Scripts) (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781250178664",
    title: "The Fire: A Novel",
    author: "Kristin Hannah",
    price: 30,
    tags: ["coming-soon", "fiction", "hardcover"],
    img_src: COVER("9781250178664"),
    img_alt: "Cover of The Fire: A Novel",
  },
  {
    isbn13: "9798217374274",
    title: "Project Hail Mary (Deluxe Edition): A Novel",
    author: "Andy Weir",
    price: 37,
    tags: ["coming-soon", "fiction", "special-edition"],
    img_src: COVER("9798217374274"),
    img_alt: "Cover of Project Hail Mary (Deluxe Edition): A Novel",
  },
  {
    isbn13: "9780593838396",
    title: "Fourth Wing, The Graphic Novel: Volume One (Deluxe Signed Edition)",
    author: "Rebecca Yarros",
    price: 65,
    tags: ["coming-soon", "fiction", "special-edition"],
    img_src: COVER("9780593838396"),
    img_alt: "Cover of Fourth Wing, The Graphic Novel: Volume One (Deluxe Signed Edition)",
  },
  {
    isbn13: "9780063579026",
    title: "Stormside (Deluxe Limited Edition) (Signed B&N Exclusive Book)",
    author: "Alex Aster",
    price: 38,
    tags: ["coming-soon", "fiction", "signed"],
    img_src: COVER("9780063579026"),
    img_alt: "Cover of Stormside (Deluxe Limited Edition) (Signed B&N Exclusive Book)",
  },
  {
    isbn13: "9781101668764",
    title: "Modern Classic (Signed Book)",
    author: "Emily Henry",
    price: 32,
    tags: ["coming-soon", "fiction", "signed"],
    img_src: COVER("9781101668764"),
    img_alt: "Cover of Modern Classic (Signed Book)",
  },
  {
    isbn13: "9780063589506",
    title: "The Ballad of Falling Dragons (Deluxe Limited Edition) (The Moonfall Series #2) (B&N Exclusive Edition)",
    author: "Sarah A. Parker",
    price: 34,
    tags: ["coming-soon", "fiction", "exclusive"],
    img_src: COVER("9780063589506"),
    img_alt: "Cover of The Ballad of Falling Dragons (Deluxe Limited Edition) (The Moonfall Series #2) (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781628866261",
    title: "Bad Idea (Deluxe Edition) (B&N Exclusive Edition)",
    author: "Elle Kennedy",
    price: 16.99,
    tags: ["coming-soon", "fiction", "exclusive"],
    img_src: COVER("9781628866261"),
    img_alt: "Cover of Bad Idea (Deluxe Edition) (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781538780046",
    title: "A Married Little Christmas (Deluxe Edition)",
    author: "Abby Jimenez",
    price: 25,
    tags: ["coming-soon", "fiction", "hardcover"],
    img_src: COVER("9781538780046"),
    img_alt: "Cover of A Married Little Christmas (Deluxe Edition)",
  },
  {
    isbn13: "9781250289773",
    title: "Once Upon a Broken Heart Collector's Edition: [Limited Stenciled Edge edition]",
    author: "Stephanie Garber",
    price: 37,
    tags: ["coming-soon", "fiction", "hardcover"],
    img_src: COVER("9781250289773"),
    img_alt: "Cover of Once Upon a Broken Heart Collector's Edition: [Limited Stenciled Edge edition]",
  },
  {
    isbn13: "9781250474933",
    title: "The Mirror of Infinite Endings (B&N Exclusive Edition): A Once Upon a Broken Heart Companion",
    author: "Stephanie Garber",
    price: 21.99,
    tags: ["special-edition", "fiction", "exclusive"],
    img_src: COVER("9781250474933"),
    img_alt: "Cover of The Mirror of Infinite Endings (B&N Exclusive Edition): A Once Upon a Broken Heart Companion",
  },
  {
    isbn13: "9780063512399",
    title: "Escape Me (Deluxe Limited Edition)",
    author: "Tahereh Mafi",
    price: 22.99,
    tags: ["special-edition", "fiction"],
    img_src: COVER("9780063512399"),
    img_alt: "Cover of Escape Me (Deluxe Limited Edition)",
  },
  {
    isbn13: "9781668271650",
    title: "How to Survive Camping: The Man With No Shadow (B&N Exclusive Edition)",
    author: "Bonnie Quinn",
    price: 10,
    tags: ["special-edition", "fiction", "exclusive"],
    img_src: COVER("9781668271650"),
    img_alt: "Cover of How to Survive Camping: The Man With No Shadow (B&N Exclusive Edition)",
  },
  {
    isbn13: "9780525556657",
    title: "Hollywood, Ending (Signed Edition)",
    author: "John Green",
    price: 27,
    tags: ["special-edition", "signed"],
    img_src: COVER("9780525556657"),
    img_alt: "Cover of Hollywood, Ending (Signed Edition)",
  },
  {
    isbn13: "9780063462540",
    title: "The Sixth Faction Deluxe Limited Edition",
    author: "Veronica Roth",
    price: 22.99,
    tags: ["special-edition", "fiction"],
    img_src: COVER("9780063462540"),
    img_alt: "Cover of The Sixth Faction Deluxe Limited Edition",
  },
  {
    isbn13: "9780063430464",
    title: "Grim Tidings: A Novel",
    author: "B.K. Borison",
    price: 16.99,
    tags: ["special-edition", "fiction", "paperback"],
    img_src: COVER("9780063430464"),
    img_alt: "Cover of Grim Tidings: A Novel",
  },
  {
    isbn13: "9781250473196",
    title: "Dead Beat (B&N Exclusive Edition)",
    author: "Leigh Bardugo",
    price: 26.99,
    tags: ["special-edition", "exclusive"],
    img_src: COVER("9781250473196"),
    img_alt: "Cover of Dead Beat (B&N Exclusive Edition)",
  },
  {
    isbn13: "9780316573757",
    title: "The Knight and the Moth",
    author: "Rachel Gillig",
    price: 16.99,
    tags: ["special-edition", "fiction", "paperback"],
    img_src: COVER("9780316573757"),
    img_alt: "Cover of The Knight and the Moth",
  },
  {
    isbn13: "9781368119399",
    title: "The Art of Gravity Falls (B&N Exclusive Edition)",
    author: "Alex Hirsch, Rob Renzetti",
    price: 55,
    tags: ["special-edition", "nonfiction", "exclusive"],
    img_src: COVER("9781368119399"),
    img_alt: "Cover of The Art of Gravity Falls (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781577158448",
    title: "The Rider Files: Official Fourth Wing Activity & Sticker Book - Based on the Award-Winning Empyrean series",
    author: "Entangled, Walter Foster Creative Team",
    price: 16.99,
    tags: ["new-release", "paperback-pick", "nonfiction", "paperback"],
    img_src: COVER("9781577158448"),
    img_alt: "Cover of The Rider Files: Official Fourth Wing Activity & Sticker Book - Based on the Award-Winning Empyrean series",
  },
  {
    isbn13: "9781250348258",
    title: "The Zorg: A Tale of Greed and Murder That Inspired the Abolition of Slavery",
    author: "Siddharth Kara",
    price: 17,
    tags: ["new-release", "paperback-pick", "nonfiction", "paperback"],
    img_src: COVER("9781250348258"),
    img_alt: "Cover of The Zorg: A Tale of Greed and Murder That Inspired the Abolition of Slavery",
  },
  {
    isbn13: "9780593199343",
    title: "Twelve Months (Dresden Files Series #18)",
    author: "Jim Butcher",
    price: 19,
    tags: ["new-release", "paperback-pick", "fiction", "paperback"],
    img_src: COVER("9780593199343"),
    img_alt: "Cover of Twelve Months (Dresden Files Series #18)",
  },
  {
    isbn13: "9780593540992",
    title: "All the Way to the River: Oprah's Book Club: Love, Loss, and Liberation",
    author: "Elizabeth Gilbert",
    price: 18,
    tags: ["new-release", "paperback-pick", "nonfiction", "paperback"],
    img_src: COVER("9780593540992"),
    img_alt: "Cover of All the Way to the River: Oprah's Book Club: Love, Loss, and Liberation",
  },
  {
    isbn13: "9781538772782",
    title: "Circle of Days",
    author: "Ken Follett",
    price: 21.99,
    tags: ["new-release", "paperback-pick", "fiction", "paperback"],
    img_src: COVER("9781538772782"),
    img_alt: "Cover of Circle of Days",
  },
  {
    isbn13: "9781250178640",
    title: "The Women: A Novel",
    author: "Kristin Hannah",
    price: 18,
    tags: ["new-release", "paperback-pick", "fiction", "paperback"],
    img_src: COVER("9781250178640"),
    img_alt: "Cover of The Women: A Novel",
  },
  {
    isbn13: "9780593804636",
    title: "Dream Count: A Novel (B&N Exclusive Edition)",
    author: "Chimamanda Ngozi Adichie",
    price: 32,
    tags: ["new-release", "paperback-pick", "fiction", "exclusive"],
    img_src: COVER("9780593804636"),
    img_alt: "Cover of Dream Count: A Novel (B&N Exclusive Edition)",
  },
  {
    isbn13: "9781668094723",
    title: "Mother Mary Comes to Me",
    author: "Arundhati Roy",
    price: 18,
    tags: ["new-release", "paperback-pick", "nonfiction", "paperback"],
    img_src: COVER("9781668094723"),
    img_alt: "Cover of Mother Mary Comes to Me",
  },
  {
    isbn13: "9780062200617",
    title: "King Sorrow: A Novel",
    author: "Joe Hill",
    price: 21,
    tags: ["new-release", "paperback-pick", "fiction", "paperback"],
    img_src: COVER("9780062200617"),
    img_alt: "Cover of King Sorrow: A Novel",
  },
  {
    isbn13: "9781538768471",
    title: "Big Dumb Eyes: Stories from a Simpler Mind",
    author: "Nate Bargatze",
    price: 17.99,
    tags: ["new-release", "paperback-pick", "nonfiction", "paperback"],
    img_src: COVER("9781538768471"),
    img_alt: "Cover of Big Dumb Eyes: Stories from a Simpler Mind",
  },
  {
    isbn13: "9781101910177",
    title: "Bread of Angels: A Memoir",
    author: "Patti Smith",
    price: 18,
    tags: ["new-release", "paperback-pick", "nonfiction", "paperback"],
    img_src: COVER("9781101910177"),
    img_alt: "Cover of Bread of Angels: A Memoir",
  },
  {
    isbn13: "9780593443552",
    title: "Bag Man: The Wild Crimes, Audacious Cover-Up, and Spectacular Downfall of a Brazen Crook in the White House",
    author: "Rachel Maddow, Michael Yarvitz",
    price: 18,
    tags: ["new-release", "paperback-pick", "nonfiction", "paperback"],
    img_src: COVER("9780593443552"),
    img_alt: "Cover of Bag Man: The Wild Crimes, Audacious Cover-Up, and Spectacular Downfall of a Brazen Crook in the White House",
  },
  {
    isbn13: "9781250479716",
    title: "Murdle Heist: 56 Clever Capers to Crack with Logic (B&N Exclusive Edition)",
    author: "G. T. Karber",
    price: 18,
    tags: ["new-release", "paperback-pick", "nonfiction", "exclusive"],
    img_src: COVER("9781250479716"),
    img_alt: "Cover of Murdle Heist: 56 Clever Capers to Crack with Logic (B&N Exclusive Edition)",
  },
  {
    isbn13: "9780593298039",
    title: "Shadow Ticket: A Novel",
    author: "Thomas Pynchon",
    price: 18,
    tags: ["new-release", "paperback-pick", "fiction", "paperback"],
    img_src: COVER("9780593298039"),
    img_alt: "Cover of Shadow Ticket: A Novel",
  },
  {
    isbn13: "9780593804216",
    title: "Yesteryear (GMA Book Club Pick)",
    author: "Caro Claire Burke",
    price: 25,
    tags: ["trending", "fiction", "hardcover"],
    img_src: COVER("9780593804216"),
    img_alt: "Cover of Yesteryear (GMA Book Club Pick)",
  },
  {
    isbn13: "9780593726259",
    title: "Hollow Bones: A Novel",
    author: "Jodi Picoult",
    price: 23.8,
    tags: ["trending", "fiction", "hardcover"],
    img_src: COVER("9780593726259"),
    img_alt: "Cover of Hollow Bones: A Novel",
  },
  {
    isbn13: "9780385550345",
    title: "The Pirate Queen",
    author: "Ariel Lawhon",
    price: 29,
    tags: ["trending", "fiction", "hardcover"],
    img_src: COVER("9780385550345"),
    img_alt: "Cover of The Pirate Queen",
  },
  {
    isbn13: "9780063443914",
    title: "The Steps: A Memoir",
    author: "Sylvester Stallone",
    price: 27.5,
    tags: ["trending", "nonfiction", "hardcover"],
    img_src: COVER("9780063443914"),
    img_alt: "Cover of The Steps: A Memoir",
  },
  {
    isbn13: "9781538752036",
    title: "American Hagwon",
    author: "Min Jin Lee",
    price: 31,
    tags: ["trending", "hardcover"],
    img_src: COVER("9781538752036"),
    img_alt: "Cover of American Hagwon",
  },
  {
    isbn13: "9780593717202",
    title: "The Disappearers: A Novel",
    author: "Marlon James",
    price: 32,
    tags: ["trending", "fiction", "hardcover"],
    img_src: COVER("9780593717202"),
    img_alt: "Cover of The Disappearers: A Novel",
  },
  {
    isbn13: "9780063579811",
    title: "Taipei Story: A Novel (B&N Exclusive Edition)",
    author: "R. F. Kuang",
    price: 29,
    tags: ["trending", "fiction", "exclusive"],
    img_src: COVER("9780063579811"),
    img_alt: "Cover of Taipei Story: A Novel (B&N Exclusive Edition)",
  },
  {
    isbn13: "9798217209460",
    title: "Exit Party: A Novel (B&N Exclusive Edition)",
    author: "Emily St. John Mandel",
    price: 29,
    tags: ["trending", "fiction", "exclusive"],
    img_src: COVER("9798217209460"),
    img_alt: "Cover of Exit Party: A Novel (B&N Exclusive Edition)",
  },
  {
    isbn13: "9780063578074",
    title: "Murder at the Grand Alpine Hotel: The New Miss Marple Mystery (B&N Exclusive Edition)",
    author: "Lucy Foley, Agatha Christie",
    price: 27,
    tags: ["trending", "fiction", "exclusive"],
    img_src: COVER("9780063578074"),
    img_alt: "Cover of Murder at the Grand Alpine Hotel: The New Miss Marple Mystery (B&N Exclusive Edition)",
  },
];
